# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabes_app', '0002_officer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='resident',
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(default='please add street name', max_length=50),
        ),
    ]
