# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabes_app', '0003_auto_20161214_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='primary_last_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
