# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabes_app', '0006_auto_20161217_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='family_members',
            field=models.CharField(default='No family members listed yet', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='primary_phone',
            field=models.CharField(default='xxx-xxx-xxxx', max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='secondary_last_name',
            field=models.CharField(default='secondary last name optional', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='secondary_phone',
            field=models.CharField(default='xxx-xxx-xxxx', max_length=12),
        ),
    ]
