# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabes_app', '0008_auto_20161217_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='headline',
            field=models.CharField(default='Month: Highlight here', max_length=50),
        ),
    ]
