# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabes_app', '0009_newsletter_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpost',
            name='headline',
            field=models.CharField(default='Write a headline', max_length=60),
        ),
    ]
