# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabes_app', '0011_auto_20161218_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.AlterField(
            model_name='profile',
            name='secondary_last_name',
            field=models.CharField(default='secondary last name optional', max_length=20, null=True),
        ),
    ]
