# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabes_app', '0012_auto_20161218_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='family_members',
            field=models.CharField(blank=True, default='optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_phone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='secondary_last_name',
            field=models.CharField(blank=True, default='optional', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='secondary_phone',
            field=models.CharField(blank=True, default='optional', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.CharField(default='', max_length=50),
        ),
    ]
