# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabes_app', '0014_auto_20161220_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='document',
            field=models.FileField(max_length=200, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='check',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family_members',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='membership_status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='paypal',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_phone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='secondary_last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='secondary_phone',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
    ]
