# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabes_app', '0016_auto_20161230_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='headline',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='memberpost',
            name='headline',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='publicpost',
            name='headline',
            field=models.CharField(default='', max_length=60),
        ),
    ]
