# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nabes_app', '0017_auto_20170102_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='number',
            new_name='house_number',
        ),
    ]
