# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabes_app', '0018_auto_20170102_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='family_members',
            new_name='family_member_names',
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.CharField(choices=[('Allison Court', 'Allison Court'), ('Badger Run', 'Badger Run'), ('Blades Trail', 'Blades Trail'), ('Blue Water Court', 'Blue Water Court'), ('Border Creek Court', 'Border Creek Court'), ('Bradford Lane', 'Bradford Lane'), ('Burton Lane', 'Burton Lane'), ('Chapel View Court', 'Chapel View Court'), ('Deer Run', 'Deer Run'), ('Dimple Court', 'Dimple Court'), ('Fairfield Forest Road', 'Fairfield Forest Road'), ('Fox Run', 'Fox Run'), ('Gold Springs Way', 'Gold Springs Way'), ('Golf Course Drive North', 'Golf Course Drive North'), ('Golf Course Drive South', 'Golf Course Drive South'), ('Green Cove Court', 'Green Cove Court'), ('Holly Court', 'Holly Court'), ('Howard Lane', 'Howard Lane'), ('Island View Court', 'Island View Court'), ('Lake Shore Road North', 'Lake Shore Road North'), ('Lake Shore Road South', 'Lake Shore Road South'), ('Lakeview Drive', 'Lakeview Drive'), ('Las Brisas', 'Las Brisas'), ("Miner's Cove Court", 'Miners Cove Court'), ('Niblick Court', 'Niblick Court'), ('Nine Iron Court', 'Nine Iron Court'), ('Norman Court', 'Norman Court'), ('North Highway 16', 'North Highway 16'), ('Pine Glade Drive', 'Pine Glade Drive'), ('Placid Court', 'Placid Court'), ('Sand Wedge Court', 'Sand Wedge Court'), ('Shanklin Lane', 'Shanklin Lane'), ('Shiny Leaf Drive', 'Shiny Leaf Drive'), ('Three Wood Drive', 'Three Wood Drive'), ('Westcape Drive', 'Westcape Drive'), ('Woodland Court', 'Woodland Court')], default='', max_length=50),
        ),
    ]
