# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabes_app', '0020_auto_20170203_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicpost',
            name='published',
        ),
        migrations.AddField(
            model_name='publicpost',
            name='priority',
            field=models.CharField(blank=True, choices=[('Top', 'Top'), ('Middle', 'Middle'), ('Bottom', 'Bottom'), ('Hidden', 'Hidden')], max_length=10, null=True),
        ),
    ]
